---
title: "Supporting references"
description: >
  Learn how to get started with the basics of pkgdown.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Supporting references}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Supporting References 

`diveRpine` was built using results and information from scientific papers published in scientific journals. Most of the papers deal with the naturalization of pine plantation forests in Sierra Nevdada mountain (Southern Spain), although other references were also used. To get detailed information about see the documentation of functions created for `diveRpine`. Here 
there is a list of the references used: 

- Gómez, J. M. (2003). Spatial patterns in long-distance dispersal of Quercus ilex acorns by jays in a heterogeneous landscape. Ecography, 26(5), 573–584. doi: [10.1034/j.1600-0587.2003.03586.x](https://dx.doi.org/10.1034/j.1600-0587.2003.03586.x)

- Gómez-Aparicio, L., Zavala, M. A., Bonet, F. J., & Zamora, R. (2009). Are pine plantations valid tools for restoring Mediterranean forests? An assessment along abiotic and biotic gradients. Ecological Applications, 19(8), 2124–2141. doi: [10.1890/08-1656.1](https://dx.doi.org/10.1890/08-1656.1)

- González-Moreno, P., Quero, J. L., Poorter, L., Bonet, F. J., & Zamora, R. (2011). Is spatial structure the key to promote plant diversity in Mediterranean forest plantations? Basic and Applied Ecology, 12(3), 251–259. doi: [10.1016/j.baae.2011.02.012](https://dx.doi.org/10.1016/j.baae.2011.02.012)

- González-Varo, J. P., López-Bao, J. V., & Guitián, J. (2013). Functional diversity among seed dispersal kernels generated by carnivorous mammals. Journal of Animal Ecology, 82(3), 562–571. doi: [10.1111/1365-2656.12024](https://dx.doi.org/10.1111/1365-2656.12024)

- Jordano, P., García, C., Godoy, J. A., & García-Castaño, J. L. (2007). Differential contribution of frugivores to complex seed dispersal patterns. Proceedings of the National Academy of Sciences, 104(9), 3278–3282. doi: [10.1073/pnas.0606793104](https://dx.doi.org/10.1073/pnas.0606793104)

- Matías, L., Zamora, R., Mendoza, I., & Hódar, J. A. (2010). Seed dispersal patterns by large frugivorous mammals in a degraded mosaic landscape. Restoration Ecology, 18(5), 619–627. doi: [j.1526-100X.2008.00475.x](https://doi.org/10.1111/j.1526-100X.2008.00475.x)

- Mendoza, I., Gómez-Aparicio, L., Zamora, R., & Matías, L. (2009). Recruitment limitation of forest communities in a degraded Mediterranean landscape. Journal of Vegetation Science, 20(2), 367–376. doi: [10.1111/j.1654-1103.2009.05705.x](https://doi.org/10.1111/j.1654-1103.2009.05705.x)

- Navarro-González, I., Pérez-Luque, A. J., Bonet, F. J., & Zamora, R. (2013). The weight of the past: land-use legacies and recolonization of pine plantations by oak trees. Ecological Applications, 23(6), 1267–1276. doi: [10.1890/12-0459.1](https://dx.doi.org/10.1890/12-0459.1)

- Pérez-Luque, Antonio Jesús, Bonet, F. J., Pérez-Pérez, R., Aspizua, R., Lorite, J., & Zamora, R. (2014). Sinfonevada: Dataset of floristic diversity in Sierra Nevada forests (SE Spain). PhytoKeys, 35, 1–15. doi: [10.3897/phytokeys.35.6363](https://dx.doi.org/10.3897/phytokeys.35.6363)

- Pérez-Luque, Antonio Jesus, Bonet-García, F. J., & Zamora Rodríguez, R. (2019). Map of ecosystems types in Sierra Nevada mountain (southern Spain). doi: [10.1594/PANGAEA.910176](https://doi.pangaea.de/10.1594/PANGAEA.910176)

- Pons, J., & Pausas, J. G. (2007). Acorn dispersal estimated by radio-tracking. Oecologia, 153(4), 903–911. doi: [10.1007/s00442-007-0788-x](https://dx.doi.org/10.1007/s00442-007-0788-x)

- Zamora, R., Hódar, J. A., Matías, L., & Mendoza, I. (2010). Positive adjacency effects mediated by seed disperser birds in pine plantations. Ecological Applications, 20(4), 1053–1060. doi: [10.1890/09-0055.1](https://dx.doi.org/10.1890/09-0055.1)
